export {default as Home} from './home/Home'
export {default as Service} from './services/Service'
export {default as About} from './about/About'
export {default as Contact} from './contact/Contact'
export {default as Courses} from './courses/Courses'